---
- name: Debian - Ensure apt-transport-https is installed
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    cache_valid_time: 86400
  when: use_repository | bool
  register: beat_install
  until: beat_install is succeeded
  notify: restart the service

- name: Debian - Ensure python-urllib3, python-openssl, python-pyasn1 & python-pip are installed
  become: true
  ansible.builtin.apt:
    name:
      - python-urllib3
      - python-openssl
      - python-pyasn1
      - python-pip
    state: present
  register: libs_install
  until: libs_install is succeeded
  when:
    - use_repository | bool
    - ansible_distribution_release == "trusty"

- name: Debian - ensure ndg-httpsclient pip is installed
  become: true
  ansible.builtin.pip:
    name: ndg-httpsclient
    state: present
  register: ndg_install
  until: ndg_install is succeeded
  when:
    - use_repository | bool
    - ansible_distribution_release == "trusty"

- name: Install beats repo key
  ansible.builtin.get_url:
    url: "{{ elastic_repo_key_url }}"
    dest: "{{ elastic_repo_key_file_path }}"
    owner: root
    group: root
    mode: "0644"
  register: deb822_apt_key_install
  until: deb822_apt_key_install is succeeded
  when: beats_add_repository | bool and not ansible_check_mode

- name: Adding apt repository for beats
  ansible.builtin.copy:
    dest: "{{ elastic_repo_file_path }}"
    owner: root
    group: root
    mode: "0644"
    content: |
      Types: deb
      Enabled: yes
      URIs: {{ elastic_repo_url }}
      Suites: stable
      Components: {{ elastic_repo_component }}
      Architectures: {{ 'amd64' if ansible_machine != 'aarch64' else 'arm64' }}
      Signed-By: {{ elastic_repo_key_file_path }}
  register: deb822_repo_install
  until: deb822_repo_install is succeeded
  when: beats_add_repository | bool

- name: Debian - Check if {{ beat }} package is installed
  ansible.builtin.package_facts:
    manager: apt

- name: Debian - unhold {{ beat }} version for install
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ beat }}"
    selection: "install"
  when: beat in ansible_facts.packages
  changed_when: false

- name: Debian - Ensure {{ beat }} is installed
  become: true
  ansible.builtin.apt:
    name: >-
      {{ beat }}{% if beats_version is defined and beats_version | length > 0 %}={{ beats_version }}{% endif %}
    state: present
    cache_valid_time: 86400
  register: beat_install
  until: beat_install is succeeded
  when: use_repository | bool
  notify: restart the service

- name: Debian - hold {{ beat }} version
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ beat }}"
    selection: "hold"
  when: version_lock
  changed_when: false

- name: Set os_arch
  ansible.builtin.set_fact:
    os_arch: >-
      {{ ansible_architecture == 'x86_64' | ternary('amd64', 'i386') }}

- name: Debian - Download {{ beat }} from url
  ansible.builtin.get_url:
    url: >-
      {% if custom_package_url is defined %}{{ custom_package_url }}{%
        else %}{{ beats_package_url }}/{{ beat }}/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb{% endif %}
    dest: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
    mode: '0644'
    owner: root
    group: root
    validate_certs: false
  when: not use_repository | bool

- name: Debian - Ensure {{ beat }} is installed from downloaded package
  become: true
  ansible.builtin.apt:
    deb: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
  when: not use_repository | bool
  notify: restart the service
