---
# tasks file for beats

- name: Check-parameters
  ansible.builtin.include_tasks: beats-param-check.yml

- name: Define beat product
  ansible.builtin.set_fact:
    beat_product: "{{ beat }}"

- name: OS-specific vars
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Install beats
  ansible.builtin.include_tasks: beats.yml
