---
# tasks file for beats

- name: Check-parameters
  ansible.builtin.include_tasks: beats-param-check.yml

- name: Define beat product
  ansible.builtin.set_fact:
    beat_product: "{{ beat }}"

- name: OS-specific vars
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Install beats
  ansible.builtin.include_tasks: beats.yml

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
