---
# handlers file for beats

- name: Restart the service
  become: true
  ansible.builtin.service:
    name: "{{ beat_product }}"
    state: restarted
    enabled: true
  when: start_service and restart_on_change and not beats_started.changed
